# 智能 qBittorrent 限速控制器配置

lucky_devices:
  - name: "我的Lucky设备"
    api_url: "http://192.168.2.3:16601/api/webservice/rules?openToken=S9SXzQAAg03myzAfUsLkiQmTBUUUr3Yn"
    weight: 1.0  # 权重：1.0=正常，0.5=减半影响，2.0=加倍影响
    enabled: true
    description: "主要监控设备"
  
  # 示例：多设备配置（注释掉，需要时取消注释）
  # - name: "次要Lucky设备"
  #   api_url: "http://192.168.2.4:16601/api/webservice/rules?openToken=YOUR_TOKEN"
  #   weight: 0.5  # 权重减半，影响较小
  #   enabled: false
  #   description: "次要监控设备"

# 更新为您的实际qBittorrent地址
qbittorrent_instances:
  - name: "我的QB实例"
    host: "http://192.168.1.101:8080"  # 改为您实际的QB地址
    username: "admin"
    password: "adminadmin"
    enabled: true
    description: "qBittorrent测试"

controller_settings:
  poll_interval: 1  # 减少到1秒，提高响应速度
  limit_on_delay: 5
  limit_off_delay: 30
  retry_interval: 10
  limited_download: 1024
  limited_upload: 512
  normal_download: 0
  normal_upload: 0

# Web服务器设置
web_settings:
  host: "0.0.0.0"  # 绑定到所有网络接口，允许外部访问
  port: 5000       # 服务端口
